name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xu-cheng/latex-action@v3
        name: "Compile document"
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: true
          args: -pdf -f
          extra_fonts: |
            ./fonts/*
          post_compile: "cp build/main.pdf main.pdf"

      - name: Rename main.pdf
        run: |
          r=$(git describe --tags --always)
          mv main.pdf ${r}.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-pdf
          path: ./*.pdf
