name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  compile:
    uses: ./.github/workflows/compile.yml

  upload:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-pdf

      - name: Rename main.pdf
        run: |
          r=$(git describe --tags --always)
          mv main.pdf ${r}.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-pdf-renamed
          path: ./*.pdf
