name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        name: Enable docker cache
        
      - uses: iwishiwasaneagle/latex-action@main
        name: "Compile document 1/2"
        with:
          root_file: main.tex
          args: -synctex=1 -interaction=nonstopmode -file-line-error -pdf
        
      - uses: iwishiwasaneagle/latex-action@main
        name: "Compile document 2/2"
        with:
          root_file: main.tex
          args: -synctex=1 -interaction=nonstopmode -file-line-error -pdf
          pre_compile: "bibtex main; makeindex main.nlo -s nomencl.ist -o main.nls"
          post_compile: "latexmk -c"
